#
# Copyright (c) 2023 Sung Ho Park and CSOS
#
# SPDX-License-Identifier: Apache-2.0
#

# ubinos_config_info {"name_base": "tflite_person_detection", "build_type": "cmake_ubinos", "app": true}

set_cache(UBINOS__BSP__LINKSCRIPT_FILE "${PROJECT_UBINOS_DIR}/source/ubinos/bsp/arch/arm/cortexm/nrf52/xxaa/flash_bdh_align16.ld" PATH)

set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_FLAG FALSE BOOL)

set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_DMPM FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_DMPM_DIR_ON_OFF FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_DMPM_MEMORY_READY_CHECK FALSE BOOL)

set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__BESTFIT FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__FIRSTFIT FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__NEXTFIT FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__PGROUP FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__GROUP FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__BBUDDY FALSE BOOL)
set_cache(UBINOS__UBICLIB__EXCLUDE_HEAP_ALGORITHM__WBUDDY FALSE BOOL)

# set_cache(UBINOS__UBICLIB__HEAP_DIR0_ALGORITHM "GROUP" STRING)
# set_cache(UBINOS__UBICLIB__HEAP_DIR0_LOCKTYPE "MUTEX" STRING)
# set_cache(UBINOS__UBICLIB__HEAP_DIR0_M 8 STRING)
# set_cache(UBINOS__UBICLIB__HEAP_DIR0_FBLCOUNT 226 STRING)
# set_cache(UBINOS__UBICLIB__HEAP_DIR0_FBLBM_BUFSIZE 36 STRING)

set_cache(UBINOS__UBICLIB__HEAP_DIR0_ALGORITHM "BESTFIT" STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR0_LOCKTYPE "MUTEX" STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR0_M 2 STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR0_FBLCOUNT 2 STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR0_FBLBM_BUFSIZE 4 STRING)

set_cache(UBINOS__UBICLIB__HEAP_DIR1_ALGORITHM "BESTFIT" STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR1_LOCKTYPE "MUTEX" STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR1_M 2 STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR1_FBLCOUNT 2 STRING)
set_cache(UBINOS__UBICLIB__HEAP_DIR1_FBLBM_BUFSIZE 4 STRING)

set_cache(UBINOS__UBICLIB__HEAP_DEFAULT_DIR 1 STRING)
set_cache(UBINOS__UBICLIB__HEAP_ALIGNMENT 16 STRING)

set_cache(NRF5SDK__DTTY_NRF_UART_WRITE_BUFFER_SIZE "1024 * 20" STRING)

set_cache(TFLITE_MICRO__INTERPRETER_TYPE "UBI_HEAP_MICRO" STRING)

include(${CMAKE_CURRENT_LIST_DIR}/tflite_person_detection_nrf52840dk.cmake)
