////////


#cmakedefine01 INCLUDE__TFLITE_MICRO

#if (INCLUDE__TFLITE_MICRO == 1)

#cmakedefine01 TFLITE_MICRO__TF_LITE_DISABLE_X86_NEON
#cmakedefine01 TFLITE_MICRO__TF_LITE_STATIC_MEMORY
#cmakedefine01 TFLITE_MICRO__TF_LITE_MCU_DEBUG_LOG
#cmakedefine01 TFLITE_MICRO__TF_LITE_USE_CTIME

#cmakedefine01 TFLITE_MICRO__INCLUDE_CMSIS_NN

#endif /* (INCLUDE__TFLITE_MICRO == 1) */

