////////


#cmakedefine01 INCLUDE__TFLITE_MICRO

#if (INCLUDE__TFLITE_MICRO == 1)

#cmakedefine01 TFLITE_MICRO__TF_LITE_DISABLE_X86_NEON
#cmakedefine01 TFLITE_MICRO__TF_LITE_STATIC_MEMORY
#cmakedefine01 TFLITE_MICRO__TF_LITE_MCU_DEBUG_LOG
#cmakedefine01 TFLITE_MICRO__TF_LITE_USE_CTIME

#cmakedefine01 TFLITE_MICRO__INCLUDE_CMSIS_NN

#define TFLITE_MICRO__INTERPRETER_TYPE__MICRO 1
#define TFLITE_MICRO__INTERPRETER_TYPE__RECORDING_MICRO 2
#define TFLITE_MICRO__INTERPRETER_TYPE__UBI_MICRO 3
#define TFLITE_MICRO__INTERPRETER_TYPE__RECORDING_UBI_MICRO 4
#define TFLITE_MICRO__INTERPRETER_TYPE TFLITE_MICRO__INTERPRETER_TYPE__@TFLITE_MICRO__INTERPRETER_TYPE@

#define TFLITE_MICRO__PERSON_DETECTION_IMAGE_PROVIDER_TYPE__DUMMY 1
#define TFLITE_MICRO__PERSON_DETECTION_IMAGE_PROVIDER_TYPE__TEST01 11
#define TFLITE_MICRO__PERSON_DETECTION_IMAGE_PROVIDER_TYPE TFLITE_MICRO__PERSON_DETECTION_IMAGE_PROVIDER_TYPE__@TFLITE_MICRO__PERSON_DETECTION_IMAGE_PROVIDER_TYPE@

#endif /* (INCLUDE__TFLITE_MICRO == 1) */

