if(INCLUDE__TFLITE_MICRO)

    get_filename_component(_tmp_lib_src_dir "${TFLITE_MICRO__BASE_DIR}" ABSOLUTE)

    include_directories(${_tmp_lib_src_dir})

    add_definitions("-DCMSIS_NN")

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/c/common.c)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/fft.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/fft_io.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/fft_util.cc)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/filterbank.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/filterbank_io.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/filterbank_util.c)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/frontend.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/frontend_io.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/frontend_util.c)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/log_lut.c)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/log_scale.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/log_scale_io.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/log_scale_util.c)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/noise_reduction.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/noise_reduction_io.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/noise_reduction_util.c)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control_util.c)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/window.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/window_io.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/experimental/microfrontend/lib/window_util.c)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/core/api/op_resolver.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/core/api/tensor_utils.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/core/api/error_reporter.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/core/api/flatbuffer_conversions.cc)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/kernels/kernel_util.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/kernels/internal/quantization_util.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/kernels/internal/reference/portable_tensor_utils.cc)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/schema/schema_utils.cc)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/all_ops_resolver.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/debug_log.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/flatbuffer_utils.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/memory_helpers.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/micro_allocator.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/micro_error_reporter.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/micro_graph.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/micro_interpreter.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/micro_profiler.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/micro_string.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/micro_time.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/micro_utils.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/mock_micro_graph.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/recording_micro_allocator.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/recording_simple_memory_allocator.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/simple_memory_allocator.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/test_helpers.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/system_setup.cc)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/activations.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/activations_common.cc)
    # set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/add.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/add_n.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/arg_min_max.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/batch_to_space_nd.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/cast.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/ceil.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/circular_buffer.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/circular_buffer_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/comparisons.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/concatenation.cc)
    # set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/conv.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/conv_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/conv_test_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/cumsum.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/depth_to_space.cc)
    # set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/depthwise_conv.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/depthwise_conv_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/dequantize.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/detection_postprocess.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/elementwise.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/elu.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/ethosu.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/exp.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/expand_dims.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/fill.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/floor.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/floor_div.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/floor_mod.cc)
    # set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/fully_connected.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/fully_connected_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/gather.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/gather_nd.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/hard_swish.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/hard_swish_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/if.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/kernel_runner.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/kernel_util.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/l2_pool_2d.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/l2norm.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/leaky_relu.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/leaky_relu_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/log_softmax.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/logical.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/logical_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/logistic.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/logistic_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/maximum_minimum.cc)
    # set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/mul.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/neg.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/pack.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/pad.cc)
    # set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/pooling.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/pooling_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/prelu.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/quantize.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/quantize_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/reduce.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/reshape.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/resize_bilinear.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/round.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/shape.cc)
    # set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/softmax.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/softmax_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/space_to_batch_nd.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/space_to_depth.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/split.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/split_v.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/squeeze.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/strided_slice.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/sub.cc)
    # set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/svdf.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/svdf_common.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/tanh.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/transpose.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/transpose_conv.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/unpack.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/zeros_like.cc)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/cmsis_nn/conv.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/cmsis_nn/depthwise_conv.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/cmsis_nn/softmax.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/cmsis_nn/fully_connected.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/cmsis_nn/mul.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/cmsis_nn/pooling.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/cmsis_nn/svdf.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/cmsis_nn/add.cc)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/kernels/testdata/conv_test_data.cc)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/memory_planner/greedy_memory_planner.cc)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_lib_src_dir}/tensorflow/lite/micro/memory_planner/linear_memory_planner.cc)

    get_filename_component(_tmp_src_dir "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)

    include_directories(${_tmp_src_dir})
    include_directories(${_tmp_src_dir}/tensorflow/lite/micro/tools/make/downloads/kissfft)
    include_directories(${_tmp_src_dir}/tensorflow/lite/micro/tools/make/downloads/flatbuffers/include)
    include_directories(${_tmp_src_dir}/tensorflow/lite/micro/tools/make/downloads/gemmlowp)
    include_directories(${_tmp_src_dir}/tensorflow/lite/micro/tools/make/downloads/ruy)

    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_src_dir}/tensorflow/lite/micro/tools/make/downloads/kissfft/kiss_fft.c)
    set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_src_dir}/tensorflow/lite/micro/tools/make/downloads/kissfft/tools/kiss_fftr.c)

endif(INCLUDE__TFLITE_MICRO)

