#ifndef TENSORFLOW_LITE_MICRO_MODELS_KEYWORD_SCRAMBLED_MODEL_DATA_H_
#define TENSORFLOW_LITE_MICRO_MODELS_KEYWORD_SCRAMBLED_MODEL_DATA_H_

extern const unsigned char g_keyword_scrambled_model_data[];
extern const unsigned int g_keyword_scrambled_model_data_len;

#endif  // TENSORFLOW_LITE_MICRO_MODELS_KEYWORD_SCRAMBLED_MODEL_DATA_H_
